version: "3"

services:
  frontend:
    restart: unless-stopped
    container_name: frontend
    build:
      context: .
      dockerfile: docker/frontend/Dockerfile
    ports:
      - "3000:3000"
    networks:
      - network
volumes:
  node_modules:
networks:
  network:
    driver: bridge
